module.exports = {
  hour: [
    { value: 0 },
    { value: 1 },
    { value: 2 },
    { value: 3 },
    { value: 4 },
    { value: 5 },
    { value: 6 },
    { value: 7 },
    { value: 8 },
    { value: 9 },
    { value: 10 },
    { value: 11 },
    { value: 12 },
    { value: 13 },
    { value: 14 },
    { value: 15 },
    { value: 16 },
    { value: 17 },
    { value: 18 },
    { value: 19 },
    { value: 20 },
    { value: 21 },
    { value: 22 },
    { value: 23 }
  ],
  day: [
    { value: 1 },
    { value: 2 },
    { value: 3 },
    { value: 4 },
    { value: 5 },
    { value: 6 },
    { value: 7 },
    { value: 8 },
    { value: 9 },
    { value: 10 },
    { value: 11 },
    { value: 12 },
    { value: 13 },
    { value: 14 },
    { value: 15 },
    { value: 16 },
    { value: 17 },
    { value: 18 },
    { value: 19 },
    { value: 20 },
    { value: 21 },
    { value: 22 },
    { value: 23 },
    { value: 24 },
    { value: 25 },
    { value: 26 },
    { value: 27 },
    { value: 28 },
    { value: 29 },
    { value: 30 },
    { value: 31 }
  ],
  month: [
    { name: 'janvier', value: 1 },
    { name: 'fevrier', value: 2 },
    { name: 'mars', value: 3 },
    { name: 'avril', value: 4 },
    { name: 'mai', value: 5 },
    { name: 'juin', value: 6 },
    { name: 'juillet', value: 7 },
    { name: 'aout', value: 8 },
    { name: 'septembre', value: 9 },
    { name: 'octobre', value: 10 },
    { name: 'novembre', value: 11 },
    { name: 'décembre', value: 12 }
  ],
  year: [
    { value: 2018 },
    { value: 2019 },
    { value: 2020 }
    // { value: 2021 },
    // { value: 2022 },
    // { value: 2023 },
    // { value: 2024 },
    // { value: 2025 },
    // { value: 2026 },
    // { value: 2027 },
    // { value: 2028 },
    // { value: 2029 },
    // { value: 2030 }
  ]
}
